server:
  port: 8082

spring:
  application:
    name: enrollment-service
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
  datasource:
    url: jdbc:h2:mem:enrollmentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      studentService:
        register-health-indicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      studentService:
        max-attempts: 3
        wait-duration: 2s